### PR TITLE
meta updates

### PR DESCRIPTION
**Pull request by slhenry**
Hey Steve, I'm trying to make it easier for:
1. translators
2. setting up a new repo.

Feel free to suggest changes. Feel free to merge when you like.
Thanks!

### CODE REVIEW

**Comment by slhenry** [comment]
NOt sure why the first worked and the rest didn't -- even with I thought I reverted back to the first...

**Comment by SteveALee** [comment]
OK ill take a look 1st thing Monday. Shadi and I noticed some strangeness with netlify on thurs but was probably unrelated

**Comment by SteveALee** [comment]
> I'm not sure why the first worked and the rest didn't:

hmm  Seems to be trying to update submodules to latest. I'll need to dig in.

**Review by SteveALee — APPROVED** [review]
Looks good, but translation is not my domain :)

**Pull request merged**
